# This workflow will install dependencies and run tests.
name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

env:
  GO_VERSION: "1.22" # Attention: has to be the same as in the Dockerfile.

jobs:
  Tests:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: ${{ env.GO_VERSION }}.x
      - name: Run tests
        run: go test -race -v -mod=vendor ./...

  Checks:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: ${{ env.GO_VERSION }}.x
      - name: Get dependencies
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install golang.org/x/tools/cmd/stringer@latest
      - name: Check for missing code generation
        run: |
          go generate ./...
          git diff --exit-code || (
            echo "The generated code is out of date"
            false
          )
      - name: Vet
        run: go vet ./...
      - name: Staticcheck
        run: staticcheck -go $GO_VERSION ./...